/**
 * Create Price Parameter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3-oas3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreatePriceParameterPriceParameterDetailsInner } from './createPriceParameterPriceParameterDetailsInner';

export interface CreatePriceParameter {
  /**
   * Name of the price parameter
   */
  name?: string;
  /**
   * Type of the period for the price parameter. Allowed values are {FIFTEEN_MINUTES, ONE_HOUR, ONE_DAY, ONE_MONTH}.
   */
  periodType?: string;
  /**
   * Timezone of the price parameter
   */
  timeZone?: string;
  /**
   * List of price parameter details
   */
  priceParameterDetails?: Array<CreatePriceParameterPriceParameterDetailsInner>;
}
