/**
 * Create Price Parameter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3-oas3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreatePriceParameterPriceParameterDetailsInner {
  /**
   * Start time of the period
   */
  periodFrom: string;
  /**
   * Price for the period
   */
  price: number;
  /**
   * Indicates whether the hour is shifted for the period
   */
  shiftedHour: boolean;
}
