/**
 * Create Price Parameter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3-oas3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetPriceParameterPriceParameterDetailInfosInner } from './getPriceParameterPriceParameterDetailInfosInner';
import { GetPriceParameterPriceParameterDetailsVersionInfosInner } from './getPriceParameterPriceParameterDetailsVersionInfosInner';

export interface GetPriceParameter {
  /**
   * ID of the price parameter
   */
  id?: number;
  /**
   * Name of the price parameter
   */
  name?: string;
  /**
   * Display name of the price parameter preview
   */
  priceParameterPreviewDisplayName?: string;
  /**
   * Version of the price parameter
   */
  version?: number;
  /**
   * Type of the period for the price parameter. Allowed values are {FIFTEEN_MINUTES, ONE_HOUR, ONE_DAY, ONE_MONTH}.
   */
  periodType?: string;
  /**
   * Status of the price parameter. Allowed values are {ACTIVE, DELETED}.
   */
  status?: string;
  /**
   * Timezone of the price parameter. Allowed values are {CET, EET}.
   */
  timeZone?: string;
  /**
   * List of price parameter details version information
   */
  priceParameterDetailsVersionInfos?: Array<GetPriceParameterPriceParameterDetailsVersionInfosInner>;
  /**
   * List of price parameter detail information preview
   */
  priceParameterDetailInfos?: Array<GetPriceParameterPriceParameterDetailInfosInner>;
}
