/**
 * Create Price Parameter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-oas3-oas3.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GetPriceParameterPriceParameterDetailsVersionInfosInner {
  /**
   * ID of the price parameter details version
   */
  id: number;
  /**
   * Display name of the price parameter preview
   */
  priceParameterPreviewDisplayName: string;
  /**
   * Version of the price parameter details
   */
  version: number;
  /**
   * Creation date of the price parameter details version
   */
  createDate: string;
}
